version: '3'
services:
  pycram:
    image: intel4coro/artnie-2drpwr-2dassignments-a6f480:a108d234996e2e6572b7c69feabf2de1a7ac7bcd
    # rpwr-assignments:binder
    build:
      context: .
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    ports: 
      - 8888:8888
    privileged: true
    # user: root
    #command: start-notebook.sh --allow-root --NotebookApp.token='' --no-browser --ip=0.0.0.0
    #entrypoint: ["/home/jovyan/work/entrypoint.sh"]
    # working_dir: /home/jovyan/
    volumes:
      - ./:/home/jovyan/work
    # - /tmp/.X11-unix:/tmp/.X11-unix:rw
    # environment:
    #   - DISPLAY
      # - QT_X11_NO_MITSHM=1
    #   - NVIDIA_DRIVER_CAPABILITIES=all
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
